### ISSUE TITLE
When the code will be released?

### ISSUE THREAD

**Issue by ShuweiShao** [supersyq/SPFlowNet#1]
Hi, thanks for the great work. I am concerning about when the code will be released?

**Comment by supersyq** [comment]
> Hi, thanks for the great work. I am concerning about when the code will be released?

Thank you for your attention. The code will be released at the end of June.

**Comment by shenqildr** [comment]
Hi, thanks for the great work. It's the end of June now when the code will be released.

**Comment by supersyq** [comment]
We have
